version: '3.4'

services:
  theunnamedservices.documentstorageservice:
    image: ${DOCKER_REGISTRY-}theunnamedservicesdocumentstorageservice
    links:
      - minio
    build:
      context: .
      dockerfile: TheUnnamedServices.DocumentStorageService/Dockerfile

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: Password01
    command: server --console-address ":9001" /data

volumes:
  minio_storage: {}